### ISSUE TITLE
Potential bad model in valid test cases

### ISSUE THREAD

**Issue by apragsdale** [popsim-consortium/demes-spec#132]
This model `test-cases/valid/pulse_edge_case_02.yaml` is given as:

```YAML
time_units: generations
demes:
- name: deme1
  epochs:
  - {start_size: 1}
- name: deme2
  epochs:
  - {start_size: 1, end_time: 50}
- name: deme3
  ancestors: [deme2]
  epochs:
  - {start_size: 1}
pulses:
- {sources: [deme1], dest: deme3, proportions: [0.9], time: 50}
```

However, I think this might not be valid, because `deme3`'s existence interval is (50, 0]. I.e., the start time is non-inclusive. A model like this _could_ instead be specified with

```YAML
- name: deme3
  ancestors: [deme1, deme2]
  proportions: [0.9, 0.1]
  epochs:
  - {start_size: 1}
```

but I'm not sure that we should allow instantaneous pulses at a deme's start time.

Is there a reason why this would be a valid model as written?

**Comment by grahamgower** [comment]
Maybe we changed things, but I thought we defined a pulse as taking effect immediately after (more recent than) the time specified. Hence a pulse can't be defined at the source deme's start_time, nor at the dest deme's end_time.

These pulse edge cases were discussed briefly here:
https://github.com/popsim-consortium/demes-spec/issues/22#issuecomment-785914098

Did I get it wrong?

**Comment by apragsdale** [comment]
I see. Thanks for the clarification (and sorry I didn't see those discussions earlier - I think I had forgotten to turn on notifications for this repo until more recently).

I am a little confused about these choices, and I don't really follow the logic about why we allow pulses at the end time of sources but not dests, or at some start times but not others. If we are strict about the (start_time, end_time] half-open interval convention of deme existence times, I would think that a pulse with a time that coincides with any source or dest start time should be disallowed. But then allow pulses that coincide with any end time.

Additionally, allowing pulses at start times is a problem for discrete generation models, since the first generation that a deme exists may not be exactly the start time. Take for example a deme with start/end times of (10, 0]. The deme is "populated" for generations 9, 8, 7, 6, ..., 1, 0.

**Comment by jeromekelleher** [comment]
I'm with @apragsdale here - wouldn't it be simpler to regard pulses as happening at that precise instant, and to then just be strict about those instants being within the deme's interval?

**Comment by molpopgen** [comment]
To summarize chatting w/@apragsdale via Slack:  this comes down to an issue to which we keep returning.  For discrete models, we have defined events as happening "in between parents and offspring". Here, the parents pulse, providing ancestry to the offspring, who first exist at generation `start_time - 1`.  

This is definitely something that keeps tripping us up.

**Comment by grahamgower** [comment]
> To summarize chatting w/@apragsdale via Slack: this comes down to an issue to which we keep returning. For discrete models, we have defined events as happening "in between parents and offspring". Here, the parents pulse, providing ancestry to the offspring, who first exist at generation `start_time - 1`.
> 
> This is definitely something that keeps tripping us up.

Yes I think this is the crux of it. The pulse time has to correspond to some parent generation of the source demes and some child generation of the destination deme. The edge case(s) raised in this issue may be surprising, but I think these are just a result of having open-closed intervals that work analogously for discrete-time and continuous-time systems. Of course, any given simulator is permitted to impose *additional* constraints and thus refuse to simulate some demographic models.

**Comment by grahamgower** [comment]
To give a little more motivation for this, I think the two ways of defining the model in the original post should be equivalent. In the second model, clearly we can have deme1 as an ancestor of deme3, so we ought to be able to do the same thing with pulses. This is because in both cases the parent generation is the final generation of deme1, and the child generation is the first generation of deme3.

The demes->ms converter relies on this equivalence because complex ancestry relationships can only be modelled using pulses (well, "split lineages", aka `-es`, then immediately "join lineages", aka `-ej`). The ms->demes converter does try to convert pulses back into ancestor/descendant relationships (although this is really tricky in general).

```yaml
# /tmp/a.yaml
time_units: generations
demes:
- name: deme1
  epochs:
  - {start_size: 1}
- name: deme2
  epochs:
  - {start_size: 1, end_time: 50}
- name: deme3
  ancestors: [deme2]
  epochs:
  - {start_size: 1}
pulses:
- {sources: [deme1], dest: deme3, proportions: [0.9], time: 50}
```

```
$ python -m demes parse --ms 1 /tmp/a.yaml
-I 3 0 0 0 -es 12.5 3 0.09999999999999998 -ej 12.5 4 1 -ej 12.5 3 2
$ python -m demes ms -N0 1 $(python -m demes parse --ms 1 /tmp/a.yaml)
time_units: generations
generation_time: 1
demes:
- name: deme1
  epochs:
  - {end_time: 0, start_size: 1.0}
- name: deme2
  epochs:
  - {end_time: 0, start_size: 1.0}
- name: deme3
  start_time: 50.0
  ancestors: [deme1, deme2]
  proportions: [0.9, 0.09999999999999998]
  epochs:
  - {end_time: 0, start_size: 1.0}
```

```
$ python -m demes ms -N0 1 $(python -m demes parse --ms 1 /tmp/a.yaml) > /tmp/b.yaml
$ python -m demes ms -N0 1 $(python -m demes parse --ms 1 /tmp/b.yaml)
time_units: generations
generation_time: 1
demes:
- name: deme1
  epochs:
  - {end_time: 0, start_size: 1.0}
- name: deme2
  epochs:
  - {end_time: 0, start_size: 1.0}
- name: deme3
  start_time: 50.0
  ancestors: [deme1, deme2]
  proportions: [0.9, 0.09999999999999998]
  epochs:
  - {end_time: 0, start_size: 1.0}
```
