### ISSUE TITLE
Interpretation of multiple "identical" pulses

### ISSUE THREAD

**Issue by molpopgen** [popsim-consortium/demes-spec#155]
I came across this example today when testing something:

```yaml
time_units: generations
demes:
 - name: A
   epochs:
    - start_size: 50
 - name: B
   epochs:
    - start_size: 50
pulses:
 - sources: [A]
   dest: B
   proportions: [0.9]
   time: 25
 - sources: [A]
   dest: B
   proportions: [0.9]
   time: 25
```

Currently, `demes-python` reads the model as valid, emitting a warning that the "outcome depends on the order".  `fwdpy11` rejects the model because the total rates sum to > 1.0 of deme B's ancestry.

How should this model be interpreted?

Possibly related: #91 and #114

cc @apragsdale b/c it is relevant to the fwdpy11 code.
