### ISSUE TITLE
clarify migration rate units/meaning

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-spec#21]
We currently say "the rate of migration per generation" (which was copied from python docstrings). Is this supposed to be a proportion of the destination population? The probability that any given individual in the source population migrates in a given generation? Something else? Presumably this should be bounded above by 1.0?

**Comment by grahamgower** [comment]
This is actually confusing me. Presumably we have an equivalence between using a `pulse` migration, or alternately creating a new deme with the appropriate ancestry proportions. I.e. if we simulate either of the two files below, sampling from deme `X` at time 0, then the samples should give us no information about which file was simulated.
```yaml
description: branch then admix
time_units: generations
demes:
  - id: A
    epochs:
      - start_time: .inf
        end_time: 0
        initial_size: 100
  - id: B
    epochs:
      - start_time: 2000
        end_time: 200
        initial_size: 300
  - id: X
    ancestors: [A, B]
    proportions: [0.05, 0.95]
    epochs:
      - start_time: 200
        end_time: 0
        initial_size: 300
```

```yaml
description: branch then pulse
time_units: generations
demes:
  - id: A
    epochs:
      - start_time: .inf
        end_time: 0
        initial_size: 100
  - id: X
    epochs:
      - start_time: 2000
        end_time: 0
        initial_size: 300
pulses:
- source: A
  dest: X
  proportion: 0.05
  time: 200
```

Presumably, we should also be able to write this equivalently with a `migration` (assuming we simulate with discrete time, for proper equivalence). But what should the migration rate be to achieve this?
```yaml
description: branch then migration
time_units: generations
demes:
  - id: A
    epochs:
      - initial_size: 100
        end_time: 0
  - id: X
    epochs:
      - start_time: 2000
        initial_size: 300
        end_time: 0
migrations:
  asymmetric:
  - source: A
    dest: X
    rate: 0.05  # presumably this depends on Ne in either A or X or both.
    start_time: 200
    end_time: 201
```
