### ISSUE TITLE
Require at least one Epoch in a Deme

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#25]
Currently we're implicitly defining a single epoch via some attributes of the Deme class. From a specification/parser writing perspective, it would be considerably simpler to just required the existence of at least one epoch. So, from the examples:

```yaml
demes:
  constant_size_deme:
    initial_size: 1000
```

```yaml
demes:
  constant_size_deme:
    epochs:
    - initial_size: 1000
      end_time: 0
```

Is the first *that* much more readable than the second? Are we the models that people will be writing down to contain many demes with just one epoch?
