### ISSUE TITLE
MDM: Simultaneous pulses occur in the order specified

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#39]
Suppose we have two pulses at time t with (source, dest) = (a, b) and (b, c) respectively. Should we allow this? Should we specify that pulses SHOULD be executed in the order they are listed, so that some fraction of a's population may end up in c immediately after t?

**Comment by grahamgower** [comment]
See https://github.com/popsim-consortium/demes-python/issues/46 and the warnings added in https://github.com/popsim-consortium/demes-python/commit/42522cf60ee2acced228b6a6bc5c923814858039

**Comment by grahamgower** [comment]
Related to this, we should enforce that the sum of pulse proportions into a deme cannot exceed 1.

**Comment by grahamgower** [comment]
Simultaneous pulses are permitted, and occur in the order listed. This needs some prose in the MDM. The demes-python implementation produces a warning when pulses involving the same demes occur at the same time, but the reference implementation does not.

The following is permitted.
```yaml
time_units: generations
demes:
- name: A
  epochs:
    - start_size: 100
- name: B
  epochs:
    - start_size: 100
- name: C
  epochs:
    - start_size: 100
pulses:
- {sources: [A], dest: B, time: 10, proportions: [0.6]}
- {sources: [B], dest: C, time: 10, proportions: [0.6]}
```
