### ISSUE TITLE
HDM: symmetric migration semantics when start_time and/or end_time are omitted

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-spec#55]
What should this mean?
```yaml
time_units: generations
defaults:
  epoch: {start_size: 1000}
demes:
- id: A
- id: B
- id: C
  start_time: 100
  ancestors: [B]
migrations:
- demes: [A, B, C]
  rate: 1e-5
```

The current behaviour is that there will be no migration between A<->B before time 100, because we set the migration `start_time` to the minimum value of all participating demes' `start_time`s. This is gives a simple implementation, so I think we should keep this behaviour. But it's not necessarily the most intuitive behaviour. One could easily interpret this as meaning that A<->C and B<->C have migrants only after time 100, but A<->B has migrants at all times.
