### ISSUE TITLE
allow the value `null` to override defaults?

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-spec#76]
The following file is accepted by demes-python (and demes-c), but not the reference implementation. I forget the exact motivation for permitting `null` (which parses as a Python `None`), because clearly we could override with an empty list. But maybe `null` is required to override defaults in some other cases?

```yaml
time_units: generations
defaults:
  deme:
    ancestors: [a, b, c]
    proportions: [0.1, 0.7, 0.2]
demes:
- name: a
  ancestors: null
  proportions: []
  epochs:
  - {start_size: 1}
- name: b
  ancestors: []
  proportions: null
  epochs:
  - {start_size: 1}
- name: c
  ancestors: null
  proportions: null
  epochs:
  - {start_size: 1}
- name: x
  start_time: 100
  epochs:
  - {start_size: 1}
- name: y
  start_time: 100
  epochs:
  - {start_size: 1}
- name: z
  start_time: 100
  epochs:
  - {start_size: 1}
```

[EDIT: this is the file `test-cases/valid/toplevel_defaults_deme_03.yaml`]

**Comment by jeromekelleher** [comment]
IIUC, Semantically it comes down to whether we make a distinction between the dictionary ``{"a": None}`` and ``{}``. They do seem like different things to me.

Isn't it clearer/simpler to only do default replacments if the key is strictly not present?

**Comment by grahamgower** [comment]
> Isn't it clearer/simpler to only do default replacments if the key is strictly not present?

I think that's what we're doing. The difference in the reference implementation is that `None` is not an acceptable value for `ancestors`, whereas in demes-python this just means "no ancestors".

**Comment by grahamgower** [comment]
Ah, I think I have an example where `null` might be needed/preferred.

```yaml
time_units: generations
defaults:
  migration: {demes: ["a", "b"]}
demes:
- name: a
  epochs:
  - start_size: 100
- name: b
  epochs:
  - start_size: 100
migrations:
- demes: null
  source: a
  dest: b
  rate: 0.1
```

**Comment by jeromekelleher** [comment]
Sorry, I'm not following what this does - would you mind spelling it out a bit please?

**Comment by grahamgower** [comment]
It specifies a default value for the `demes` property of each migration.
```yaml
defaults:
  migration:
    demes: [a, b]
```

But then if we want to specify an asymmetric migration, we need need to override this default somehow.
We "unset" the `demes` property by giving it the value `null`, and then use the `source` and `dest` properties as usual.
```yaml
migrations:
- demes: null
  source: a
  dest: b
  rate: 0.1
```

 If we didn't override the default, then `demes`, `source`, and `dest` would all be defined, which would be invalid due to ambiguity about whether a symmetric or asymmetric migration is defined.

**Comment by jeromekelleher** [comment]
Hmmm. I'm not so keen on this, seems like it could be quite confusing.

How about we disallow this for the first version of the spec and add it as a "should we allow this" for the next version?

**Comment by jeromekelleher** [comment]
What's the status here @grahamgower, looks like you have some commits referring to this?

**Comment by grahamgower** [comment]
I kinda sidestepped this by removing the test case which exhibits this "feature". The reference implementation does not support "null", whereas demes-python and demes-c currently do. I'm not particularly worried about differing behaviour here.

**Comment by jeromekelleher** [comment]
I'm not so sure, it seems like a significant divergence from the spec to me. Would documents containing these ``null`` values validate against the HDM schema?

**Comment by grahamgower** [comment]
> I'm not so sure, it seems like a significant divergence from the spec to me. Would documents containing these `null` values validate against the HDM schema?

No, the examples above won't.

These are the possible actions we could take:
* Allow null in the spec. This means we need to (1) add null as an allowed type for most of the fields, and make define this to mean that the field is treated as if it were omitted entirely (ignoring any user-specified 'defaults' corresponding to the field). We also need to (2) update the reference implementation to allow this.
* Disallow null in the spec. No changes are required to the current spec or the reference implementation. Modifications need to be made in (1) demes-python and (2) demes-c. It will be impossible to set a migration `demes` key for symmetric migration and then override to get asymmetric migrations, and vice versa.
* Leave the spec as it is and leave the implementations as they are. This is unsatisfying, but is the least amount of work and might make sense if we think we'll add null to the spec in the future.

**Comment by jeromekelleher** [comment]
I don't think we can leave things as they are - the whole point of a specification is that people are supposed to agree to stick to it. I don't think the marginal benefit of allowing migrations to be specified in the way mentioned above is worth the major drawback of shipping non-conforming implementations on our 1.0 release (or the work and schema ugliness of allowing null in every field in the HDM schema).

What do others think?

**Comment by apragsdale** [comment]
I find the defaults + overriding with `null` a bit complicated, and probably confusing for most users. But it's probably something most people won't come across.

In general, it could be very useful to have `null` values for certain model parameters. I was talking with @sgravel over the weekend about getting demes working with Tracts, which is a method for inferring recent admixture scenarios. That model is entirely based on ancestry tract length distributions, and population sizes don't play a part at all, and only the timing and proportions of migration events have any effect, so I could imagine wanting to put `null` as the epoch sizes for the populations.

**Comment by grahamgower** [comment]
> I find the defaults + overriding with `null` a bit complicated, and probably confusing for most users. But it's probably something most people won't come across.

I agree that it's definitely confusing. But right now there's no other way of overriding a default without providing a value, which will necessarily limit the utility of the defaults to cases where a new value can be sensibly provided (e.g. an empty list rather than a populated list). I'm sure this null thing was mentioned somewhere before this issue, but I can't seem to find it (maybe we called it something else at the time?).

> 
> In general, it could be very useful to have `null` values for certain model parameters. I was talking with @sgravel over the weekend about getting demes working with Tracts, which is a method for inferring recent admixture scenarios. That model is entirely based on ancestry tract length distributions, and population sizes don't play a part at all, and only the timing and proportions of migration events have any effect, so I could imagine wanting to put `null` as the epoch sizes for the populations.

Hmm. Ignoring a value downstream is easy to do though, so having null here wouldn't be strictly needed would it? My guess is that accepting null as a valid value for sizes would require a *lot* of code refactoring, and that's something I'd like to avoid.

**Comment by sgravel** [comment]
Yeah, having a parameter with a null value would be clearer in that context, although not necessary.

If we decide to have labels for entries (as I just suggested [here](https://github.com/popsim-consortium/demes-paper/issues/3#issue-744911148)), we could also have a suggested default labeling scheme for unused variable labels (e.g., starting with underscore), which would presumably require no refactoring.

**Comment by jeromekelleher** [comment]
I think there's two separate issues here:

1. Allowing certain fields to have ``null`` values, which are semantically significant; and 
2. Having **all** values being assigned to null being semantically identical to missing.

It seems like (1) is something that we'll have to deal with, probably over time and subsequent schema versions (adding support for null with defined semantics, per field) is something we can do. (2) Seems like a very drastic thing to do, which basically rules out every having specific null semantics per field.

**Comment by grahamgower** [comment]
Ok, I feel like we're going around in circles a bit here. Lets add some models containing `null` to the invalid test cases, and double check that the reference implementation rejects them. We can then open issues for demes-python and demes-c to also reject these cases (but I don't see it as a high priority to fix this, because setting something to null is a fairly deliberate action that one wouldn't take by accident).

**Comment by grahamgower** [comment]
It seems that variables where the value is omitted will be implicitly given the value `null`. So, my migration example above could be written as:
```yaml
time_units: generations
description:
defaults:
  migration:
    demes: [a, b]
demes:
- name: a
  epochs:
  - start_size: 100
- name: b
  epochs:
  - start_size: 100
migrations:
- demes:  # <--- this is given the value `null`, even with a comment after it
  source: a
  dest: b
  rate: 0.1
```
