### ISSUE TITLE
Allow null values to represent "unknown" or missing data

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#88]
I'm not suggesting that we do this for version 1.0, but here's a counter-proposal for the semantics of null values to #76.

There will be situations in which key parameters are unknown, or unknowable by particular inference methods. Forcing them to specify a value would be artificial, and unhelpful. It would be better if there was an agreed-upon way of stating this, and using "null" values seems like as good a way as any.

This has some desirable properties, as simulators that don't support unknown values (if we add it in to a later version of the spec) SHOULD raise an error when an unexpected type (null) is provided for a value.

**Comment by grahamgower** [comment]
This will make it very hard to validate a model. E.g. how would the parser validate a deme that has a null start_time?

**Comment by jeromekelleher** [comment]
Yeah, we'd need to choose the supported fields with care. The main point is that there can be useful semantics we might want to hang on ``null``, which I don't think we should throw away all at once by making it equivalent to "not present".

**Comment by grahamgower** [comment]
I'll note one other thing for future us while I think of it: the Builder API in demes-python is probably not setup to permit useful semantics for `None` values, because add_deme, add_migration, etc. have params with default set to None and this currently does mean "don't set a value in the data dictionary". (The Builder API isn't used when loading a yaml file though, so no problem there)

**Comment by apragsdale** [comment]
I've been thinking about this a bit more, and I agree with Jerome that it's a lot more helpful to be able to place `null` in the scenario of unknown or unknowable parameters in the model. And this is probably a good time to settle out how it would work, when the number of supporting software is minimal and we don't have a 1.0 release out.

As for which parameters in a model we allow to be unknown, I think we can make a reasonable choice along the lines of allowing `null` for deme-specific parameters (e.g. sizes, selfing rates), but disallow `null` for parameters that determine the topology of the demography or start/end times for demes and epochs. That way we can still verify the that we have a valid model as far as ancestor/descendant relationships and that time flows properly through the graph.

Maybe we only allow this in the YAML? Or should we allow, e.g., and epoch population size to be `None` in the Builder API?

Just to give a concrete example, this would be a valid model for Tracts (cc: @sgravel, do you agree?), which doesn't use population sizes:

```YAML
description: Tracts model with no population sizes set. A, B, and C contribute to admixed deme D.
time_units: generations
demes:
- name: A
  epochs:
  - start_size: null
    end_time: 0
- name: B
  epochs:
  - start_size: null
    end_time: 0
- name: C
  epochs:
  - start_size: null
    end_time: 0
- name: D
  ancestors: [A, B]
  proportions: [0.8, 0.2]
  start_time: 10
  epochs:
  - start_size: null
    end_time: 0
pulses:
- time: 5
  source: C
  dest: D
  proportion: 0.1
```
