### ISSUE TITLE
consider features that are useful for inference

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-spec#89]
We've discussed this in various places. Here are the obvious links I found.
https://github.com/popsim-consortium/demes-python/issues/63
https://github.com/popsim-consortium/demes-paper/issues/3

**Comment by grahamgower** [comment]
Some examples of schemes currently used to specify demographic model parameters (for inference or simulation generally). Feel free to edit this post (and maybe comment to ping folks about an update).

Program | URI | Format | Expressions |  Distributions | Bounds | Constraints | Notes
-|-|-|-|-|-|-|-
moments | [docs](https://moments.readthedocs.io/en/latest/extensions/demes.html#using-demes-to-infer-demography) | YAML | no | uniform | yes | yes |
ms | [site](http://home.uchicago.edu/~rhudson1/source/mksamples.html) | N/A | no | no | no | no | Accepts the special value "tbs" for any parameter on the command line. The space-separated parameter values are then read from stdin, one line per simulation replicate. Parameter distributions are managed by the user.
fast/simcoal/2 | [manual](http://cmpg.unibe.ch/software/fastsimcoal27/man/fastsimcoal27.pdf) (pg 35) | custom | yes | uniform, log-uniform | yes | yes |  Parameters are specified as a variable name in a "template" input file that matches the regular text-based input file format. A separate "estimation" file describes parameter type (int/float), distribution, and bounds. The design looks very complicated and there are many quirks that may lead to user error.
legofit | [docs](https://alanrogers.github.io/legofit/html/index.html) | custom | yes | uniform | yes | yes | Free parameters are given default ranges if not specified. Variables have a type, e.g. "time" or "haploid population size". The design looks very clean.

**Comment by grahamgower** [comment]
https://www.yaml.info/learn/index.html#config highlights how Github Actions workflow YAML files use `${{ <expression> }}` inside the YAML to include a minilanguage that e.g. permits references to variables defined elsewhere in the YAML (without doing alias/anchor nastiness). The key point, is that the `${{ foo }}` syntax was chosen because it is parsed as a YAML string. If one was so inclined, this approach could be used by an inference framework to refer to variables and include simple arithmetic.

```yaml
time_units: generations
variables:
- {name: N0, lower: 50, upper: 1000}
- {name: T0, lower: 100, upper: 200}
demes:
- name: A
  epochs:
  - end_time: ${{ T0 }}
    start_size: ${{ N0 }}
  - end_time: 0
    start_size: ${{ 10 * N0 }}
```

And maybe allowing non-free parameters to refer to other parameters:

```yaml
time_units: generations
variables:
- {name: N0, lower: 50, upper: 1000}
- {name: T0, value: ${{ 5 * N0 }} }
demes:
- name: A
  epochs:
  - end_time: ${{ T0 }}
    start_size: ${{ N0 }}
  - end_time: 0
    start_size: ${{ 10 * N0 }}
```

The idea here would be that a static Demes model could be constructed from such a "template" (E.g. using [pyparsing](https://github.com/pyparsing/pyparsing/) to parse the expression minilanguage). I'm not convinced we want to have such a thing in the Demes spec, but I can certainly imagine having a python library that implements this.
