### ISSUE TITLE
Semantics of time_units/generation_time unclear in MDM

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#93]
It's reasonably clear what the semantics for time_units and generation_time are from the perspective of the human data model. However, I'm not clear what the semantic are  in the parsed output. One straightforward thing we could do is to get the parser to resolve to generations, but I think that's probably too reductive.

So, it's up to the simulator to check what the time units are, and to see if it likes these units, raising an error if it doesn't?

Also, it's not clear why we allow "null" as an input value here:
```
  generation_time:
    type: ["number", "null"]
    exclusiveMinimum: 0
    exclusiveMaximum: .inf
    default: null
```
Why default to null, and not simply be empty?
