### ISSUE TITLE
Pulse migrations at non-integer time values

### ISSUE THREAD

**Issue by sgravel** [popsim-consortium/demes-spec#99]
_Originally posted by @sgravel in https://github.com/popsim-consortium/demes-spec/issues/91#issuecomment-874388074_

I've edited the question following an answer by @molpopgen there. 

I  have a question about the specification for pulse migrations at non-integer time values. Consider the model

```
time_units: generations
demes:
  - name: X
    epochs:
      - end_time: 1000
        start_size: 2000
  - name: A
    ancestors: [X]
    epochs:
      - start_size: 2000
  - name: B
    ancestors: [X]
    epochs:
      - start_size: 2000
  - name: C
    ancestors: [X]
    epochs:
      - start_size: 2000

pulses:
  - source: A
    dest: B
    proportion: 0.3
    time: 10
  - source: C
    dest: B
    proportion: 0.3
    time: 10.1

```

The possibly ambiguous value is what to do with the continuous time 10.1 in the last line for a discrete generation simulator. From an answer by @molpopgen at the above issue, such pulses should probably be interpreted as happening at t=round(10.1). That seems reasonable in most cases, but is inconvenient for using demes in TRACTS. 

TRACTS implements a discrete time model where recent migration pulses from different source populations can co-occur in a given generation, and fractional generations do matter. 

If I chose selfishly, I would like a specification such that:

1-The Wright-Fisher and Kingman models are comparable if simulated from the same model according to specification (i.e., at the end of generation 10, both models have the same proportion of lineages tracing back to sources A and C). 

2-Both models work and are somewhat continuous in the continuous time parameter. 

In TRACTS, I had handled this issue by interpreting a pulse at a non-integer time t as a pulse spread over two generation, ceil(t) and floor(t), with proportions at each generation computed such that proportion of lineages that can be traced back to the pulse are as required by the pulse proportion. 

However, this would not give directly comparable results to Kingman’s in the model above. To achieve consistency, one would need to similarly split pulses under Kingman to achieve compatibility.  This is, admittedly, quite ugly. 

A (small) benefit is that you would get continuity in the time parameter, so that the following two models would be similar but distinct:

```
time_units: generations
demes:
  - name: X
    epochs:
      - end_time: 1000
        start_size: 2000
  - name: A
    ancestors: [X]
    epochs:
      - start_size: 2000
  - name: B
    ancestors: [X]
    epochs:
      - start_size: 2000
  - name: C
    ancestors: [X]
    epochs:
      - start_size: 2000

pulses:
  - source: A
    dest: B
    proportion: 0.3
    time: 10.09
  - source: C
    dest: B
    proportion: 0.3
    time: 10.1

```

would be similar to 

```
time_units: generations
demes:
  - name: X
    epochs:
      - end_time: 1000
        start_size: 2000
  - name: A
    ancestors: [X]
    epochs:
      - start_size: 2000
  - name: B
    ancestors: [X]
    epochs:
      - start_size: 2000
  - name: C
    ancestors: [X]
    epochs:
      - start_size: 2000

pulses:
  - source: A
    dest: B
    proportion: 0.3
    time: 10.1
  - source: C
    dest: B
    proportion: 0.3
    time: 10.09

```

I don't really expect that you will want to change the Kingman coalescent specs to accommodate this somewhat niche case, and I think the rounding solution suggested by @molpopgen makes sense in most applications. 

Maybe I'll just use have to use demes off-spec for this particular case, unless anyone has another idea.

**Comment by grahamgower** [comment]
I don't really know what to say about this, as I can't see whether it simplifies things or makes everything more complicated... But after thinking about your examples, it seems we've already got some awkwardness between the Kingman and Wright-Fisher cases due to rounding.

Suppose we write down pulses with the more recent pulse first.
```yaml
pulses:
  - {source: A, dest: B, proportion: 0.3, time: 10}
  - {source: C, dest: B, proportion: 0.3, time: 10.1}
```

In the continuous-time setting, the pulse from C->B is more ancient so it occurs first (forwards in time).

But in the discrete-time case, the behaviour could depend on when the rounding is done. If rounding is done before looking at pulse order, then both pulses have time 10. A->B is written first, so it "wins" and is applied first (forwards in time), which is the opposite to the continuous-time behaviour!

I think this problem also affects how pulses are resolved in your suggestion above, @sgravel? The exact resolution order would need to be very clearly described.

**Comment by sgravel** [comment]
Yeah, I don't think there is a perfect solution here. 

In the example you give, you could have the convention that the order of pulses is determined prior to rounding (so that C->B occurs first). This is reasonably natural if somewhat prone to bugs. 

In the splitting approach, one approach would be to set the proportions at generation 10 from the overall proportions and times (e.g., 0.27 = 0.3 * (1-0.1)):

```
                         A->B       C->B
generation 10          0.3            0.27
generation 11              0            0.07
```
and then adjust generation 11 so that the residual proportions after the two generations are 0.3. For example, 0.27 + 0.07*(1-0.3-0.27) = 0.03. This is also bug prone and likely has a few corner cases. 

It also means that two pulses occur at the same time,  the contributions would add up, which is not what had been decided previously. 

If we want to be flexible, would it be possible to have a default which focuses on the simplest possible behaviour applicable to most cases (probably rounding as per @molpopgen), and an alternate resolution model specified in metadata?

**Comment by apragsdale** [comment]
This makes me think that we want both the YAML parser and the builder to apply a stable sort (that preserves order of implementation of pulses occurring at the same time) on the pulse times before emitting the demes Graph. Then if a program that works in discrete time and decides to round will be guaranteed (as long as they don't reorder events) the consistent sequential order of those mass migration events.

The issue of how to ensure consistency between continuous time and discrete time models is not something we can really resolve here, I think. And different simulators maybe should be allowed to have some wiggle room in how non-integer times get translated to discrete generations. I think the best we can impose, as Simon said, is that

1) ancestry proportions are the same across different implementations and software, and
2) the timing of the pulses should occur at time < 1 generation away from when specified in the model.

The first point should be strictly followed, and the second we should just expect that it's "close enough", and rounding as in fwdpy11 or bracketing as in tracts should both be acceptable solutions.

**Comment by grahamgower** [comment]
> This makes me think that we want both the YAML parser and the builder to apply a stable sort (that preserves order of implementation of pulses occurring at the same time) on the pulse times before emitting the demes Graph. Then if a program that works in discrete time and decides to round will be guaranteed (as long as they don't reorder events) the consistent sequential order of those mass migration events.

Yes, I think you're right, we should apply a stable sort when parsing (before any rounding could be done downstream).

> The issue of how to ensure consistency between continuous time and discrete time models is not something we can really resolve here, I think. And different simulators maybe should be allowed to have some wiggle room in how non-integer times get translated to discrete generations. I think the best we can impose, as Simon said, is that
> 
> 1. ancestry proportions are the same across different implementations and software, and
> 2. the timing of the pulses should occur at time < 1 generation away from when specified in the model.
> 
> The first point should be strictly followed, and the second we should just expect that it's "close enough", and rounding as in fwdpy11 or bracketing as in tracts should both be acceptable solutions.

That's a nice pragmatic solution. In my mind, the desired behaviour for TRACTS is entirely consistent with the "spirit" or "intention" of the model. And given the difficulty in exactly specifying what happens when continuous times are converted to discrete times, we should probably accept a little wiggle room here.

**Comment by sgravel** [comment]
Agree that wiggle room within a generation should be acceptable. However, the bracketing approach I described will produce different ancestry proportions than those in a sequential model. With two pulses each with proportions 0.5 and both at the same time, the bracketing approach I described would produce a total replacement of 1, compared to 0.75 in the sequential mode.

I don't think this can be resolved easily, because in the current specification, the model is discontinuous with respect to the pulse times (when two pulses switch ordering). This is reasonable behaviour under a continuous time model, but I currently need continuous behaviour for optimization in a discrete model.       

Right now the only way I see to address all the cases is to have two kinds of pulses: a sequential pulse that deletes all that occurred earlier, and a concurrent pulse that co-occurs and adds to other pulses. This would allow users more flexibility to specify the models more transparently and without having to reverse engineer rates, but I also realize it is more overhead for a corner case. 

Before I keep harping on about this, I'll go ahead and implement the TRACTS-demes interface more fully, in case I can find a workaround.

**Comment by apragsdale** [comment]
I don't think there's an easy way around this issue, where the current model implementation in tracts plays nicely with the demes specification. I also think that you don't want to go "off-spec" in the tracts-demes implementation, because one of the goals will be to be able to take models output by tracts and simulate under that model in other software that supports tracts. If you implement a different understanding of how pulses that occur around the same time interact, that will lead to a lot of downstream headaches.

One solution, that isn't perhaps ideal for the flexibility that tracts currently provides, is when using demes to specify the input for tracts inference, you impose that the times of those pulse events can vary but the relative order must remain consistent and pulse events are applied sequentially. When you output the best fit model from tracts, you will want it to be compatible with the sequential mass migration approach in any case.

The discontinuity of pulses when they switch order is something that also occurs in moments or dadi inference as well, and it is annoying when the optimizer gets stuck because of it. It might just be that if you want to specify a model that allows the order of pulses to swap around, the input model is specified as tracts is currently set up and just the static best fit output can be given to meet the spec requirements of sequential pulses.

**Comment by apragsdale** [comment]
> With two pulses each with proportions 0.5 and both at the same time, the bracketing approach I described would produce a total replacement of 1, compared to 0.75 in the sequential mode.

In the demes spec, this would have to be proportion 1 from the first deme, and then 0.5 from the second to get full replacement.

An alternative model implementation, if you want to impose that multiple pulse occur at the same time and the proportions are cumulative instead of applied sequentially, is to create an additional deme with the relevant ancestors and proportions:

```YAML
demes:
- name: A
  epochs: {start_size: 100}
- name: B
  epochs: {start_size: 100}
- name: C
  epochs: {start_size: 100}
- name: A2
  ancestors: [A, B, C]
  proportions: [0.4, 0.3, 0.3]
  start_time: 10
  epochs: {start_size: 100}
```
